// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbdhusuyokibidemwzcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRiZGh1c3V5b2tpYmlkZW13emN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2MjIwMDMsImV4cCI6MjA5MDE5ODAwM30.do0CrRu3ay5VsQxdJdvdkByRlz9WhcD7vu8XoRTvCPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});